'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WpfApplication1.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        '''The #creature# turns towards you.
        '''
        '''Drawing your weapon, you prepare to fight.
        '''
        '''=============================================
        '''
        '''HP: #hp#	Enemy HP: #eHP#
        '''
        '''=============================================
        '''
        '''#Attacks#.
        '''</summary>
        Friend ReadOnly Property _0_1___Fight() As String
            Get
                Return ResourceManager.GetString("_0_1___Fight", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to (Set Up &apos;start&apos; and &apos;lore&apos; buttons)
        '''
        '''Welcome to &apos;Battle of the Texts&apos;, a text based game made by Matt and Will.
        '''
        '''==========================================================================
        '''
        '''Here you will enter the world of Raen, a world ravanged by decades of war.
        '''
        '''Do you have what it takes to save Raen.
        '''
        '''You can click &apos;start&apos; to begin
        '''
        '''or
        '''
        '''Click &apos;lore&apos; to read up on everything that&apos;s happened so far..
        '''</summary>
        Friend ReadOnly Property _1_1___WelcomeScreen() As String
            Get
                Return ResourceManager.GetString("_1_1___WelcomeScreen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property _1_2___Lore() As String
            Get
                Return ResourceManager.GetString("_1_2___Lore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        '''The world is foggy around you, yet you dont notice.
        '''Objects materialize around you, yet nothing seems wrong.
        '''Your suddenly at your home, in your bed, this doesnt seem odd to you.
        '''
        '''Sitting up, you look around, &quot;Today&apos;s the day.&quot; you realise, this is when you head to the Capital.
        '''To join the other Chosen, to fight the Shadows.
        '''You take a step to the door, opening it, light floods around you.
        '''
        '''You hear sounds, the crackle of a fire, the blowing of the wind;
        '''You feel ground underneath you, you&apos;re lyi [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property _2_1___Intro() As String
            Get
                Return ResourceManager.GetString("_2_1___Intro", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
